name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  preflight:
    name: Preflight - check docker image availability
    runs-on: ubuntu-latest
    outputs:
      pulled: ${{ steps.check.outputs.pulled }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Try docker pull with retries
        id: check
        run: |
          set -euo pipefail
          PULLED=false
          for i in 1 2 3; do
            echo "Attempt $i: docker pull zmkfirmware/zmk-build-arm:stable"
            if docker pull zmkfirmware/zmk-build-arm:stable; then
              PULLED=true
              break
            fi
            sleep $((i * 5))
          done
          echo "pulled=$PULLED" >> $GITHUB_OUTPUT

  build_via_reusable:
    name: Build (use container image)
    needs: preflight
    if: needs.preflight.outputs.pulled == 'true'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  build_fallback:
    name: Build fallback (install west/zephyr on runner)
    needs: preflight
    if: needs.preflight.outputs.pulled != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [tstk_tl6tn9_right, tstk_tl6tn9_left]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install west and zephyr (may take a few minutes)
        run: |
          python3 -m pip install --upgrade git+https://github.com/zephyrproject-rtos/west.git
          python3 -m pip install --upgrade git+https://github.com/zephyrproject-rtos/zephyr.git || true

      - name: Initialize and update west (use local manifest)
        run: |
          if [ -f west.yml ]; then
            west init -l . || true
          else
            west init -m https://github.com/zmkfirmware/zmk . || true
          fi
          west update || true

      - name: Ensure ZEPHYR_BASE
        run: |
          echo "ZEPHYR_BASE=$(pwd)/zephyr" >> $GITHUB_ENV

      - name: Build firmware (fallback)
        run: |
          west build -b ${{ matrix.board }} -s . -d build-${{ matrix.board }} 2>&1 | tee build-${{ matrix.board }}.log || true

      - name: Upload build debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.board }}-debug
          path: build-${{ matrix.board }}
