name: Build ZMK firmware (local)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build per-board
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["tstk_tl6tn9_left", "tstk_tl6tn9_right"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install west
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade git+https://github.com/zephyrproject-rtos/west.git || true

      - name: Initialize and update west
        run: |
          if [ -f west.yml ]; then
            west init -l . || true
          else
            west init -m https://github.com/zmkfirmware/zmk . || true
          fi
          west update || true

      - name: Build firmware
        run: |
          echo "Building for board: ${{ matrix.board }}"
          west build -b ${{ matrix.board }} -s . -d build-${{ matrix.board }} || true
                  echo 'Fallback manifest download failed; will not run west update'
