name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ...（ZMKビルドのためのセットアップやwest buildなど）...

      - name: Upload .config artifact
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-config
          path: build/zephyr/.config