name: Upload autoconf (simple)

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["tstk_tl6tn9_left", "tstk_tl6tn9_right"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install west and deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade git+https://github.com/zephyrproject-rtos/west.git
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake ninja-build zip

      - name: Init west (upstream manifest)
        run: |
          if [ -f west.yml ]; then
            west init -l . || true
            west update || true
          else
            west init -m https://github.com/zmkfirmware/zmk . || true
            west update || true
          fi

      - name: Export ZEPHYR_BASE
        run: |
          echo "ZEPHYR_BASE=$(pwd)/zephyr" >> $GITHUB_ENV

      - name: Build (generate autoconf)
        run: |
          west build -b ${{ matrix.board }} -s . -d build-${{ matrix.board }} || true

      - name: Upload autoconf
        uses: actions/upload-artifact@v4
        with:
          name: autoconf-${{ matrix.board }}
          path: build-${{ matrix.board }}/zephyr/include/generated/autoconf.h
