name: Upload autoconf artifacts

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Build ZMK firmware"]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  upload-autoconf:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    strategy:
      matrix:
        board: ["tstk_tl6tn9_left", "tstk_tl6tn9_right"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install west and cmake
        run: |
          python -m pip install --upgrade pip
          pip install west==0.13.0
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Initialize west
        run: |
          # Initialize west using upstream ZMK manifest if no local west.yml exists
          if [ -f west.yml ] || [ -f config/west.yml ]; then
            west init -l . || true
          else
            west init -m https://github.com/zmkfirmware/zmk . || true
          fi
          west update || true

      - name: Build firmware (generate autoconf)
        working-directory: .
        run: |
          # Adjust board names if your board folder uses different naming
          west build -b ${{ matrix.board }} -s . -d build-${{ matrix.board }} || true

      - name: List build directory (for debugging)
        run: |
          echo "Listing build directory for ${{ matrix.board }}"
          ls -la build-${{ matrix.board }} || true
          ls -la build-${{ matrix.board }}/zephyr || true

      - name: Find autoconf.h and other generated files
        run: |
          echo "Searching for autoconf.h under build-${{ matrix.board }}"
          find build-${{ matrix.board }} -type f -name autoconf.h -print || true
          echo "Listing any generated include directories"
          find build-${{ matrix.board }} -type d -name generated -print || true

      - name: Archive build directory (debug)
        run: |
          zip -r build-${{ matrix.board }}-debug.zip build-${{ matrix.board }} || true

      - name: Upload autoconf.h
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: autoconf-${{ matrix.board }}
          path: |
            build-${{ matrix.board }}/zephyr/include/generated/autoconf.h

            
