name: Upload autoconf artifacts

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Build ZMK firmware"]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  upload-autoconf:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    strategy:
      matrix:
        board: ["tstk_tl6tn9_left", "tstk_tl6tn9_right"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install west and cmake
        run: |
          python -m pip install --upgrade pip
          # Install west and zephyr from upstream to ensure 'west build' command is available
          pip install --upgrade git+https://github.com/zephyrproject-rtos/west.git
          pip install --upgrade git+https://github.com/zephyrproject-rtos/zephyr.git || true
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Initialize west
        run: |
          # Initialize west using upstream ZMK manifest if no local west.yml exists
          if [ -f west.yml ] || [ -f config/west.yml ]; then
            west init -l . || true
          else
            west init -m https://github.com/zmkfirmware/zmk . || true
          fi
          west update || true

      - name: Install Zephyr Python requirements and verify west
        run: |
          # Install zephyr python requirements (may exist after west update)
          if [ -d zephyr ]; then
            python -m pip install --upgrade pip
            if [ -f zephyr/scripts/requirements-base.txt ]; then
              pip install -r zephyr/scripts/requirements-base.txt || true
            fi
            if [ -f zephyr/scripts/requirements.txt ]; then
              pip install -r zephyr/scripts/requirements.txt || true
            fi
          fi
          echo '--- west version and commands (after init/update) ---'
          which west || true
          python -m pip show west || true
          west --version || true
          # ensure ZEPHYR_BASE is set so west loads zephyr extensions
          echo "ZEPHYR_BASE=$(pwd)/zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_BASE=$(pwd)/zephyr"
          west help || true

      - name: Debug west and workspace
        run: |
          echo '--- debug: which/pip show/freeze ---'
          which west || true
          python -m pip show west || true
          python -m pip show zephyr || true
          echo '--- pip freeze (top 200 lines) ---'
          python -m pip freeze | head -n 200 || true
          echo '--- .west and zephyr tree ---'
          ls -la .west || true
          if [ -d zephyr ]; then
            ls -la zephyr || true
            ls -la zephyr/scripts || true
          fi
          if [ -f .west/manifest.yml ]; then
            echo '--- .west/manifest.yml ---'; cat .west/manifest.yml || true
          fi
          echo '--- west list/config/topdir ---'
          west list || true
          west config || true
          west topdir || true

      - name: Build firmware (generate autoconf)
        working-directory: .
        run: |
          # Adjust board names if your board folder uses different naming
          west build -b ${{ matrix.board }} -s . -d build-${{ matrix.board }} 2>&1 | tee build-${{ matrix.board }}.log || true

      - name: List build directory (for debugging)
        run: |
          echo "Listing build directory for ${{ matrix.board }}"
          ls -la build-${{ matrix.board }} || true
          ls -la build-${{ matrix.board }}/zephyr || true

      - name: Find autoconf.h and other generated files
        run: |
          echo "Searching for autoconf.h under build-${{ matrix.board }}"
          find build-${{ matrix.board }} -type f -name autoconf.h -print || true
          echo "Listing any generated include directories"
          find build-${{ matrix.board }} -type d -name generated -print || true

      - name: Archive build directory (debug)
        run: |
          zip -r build-${{ matrix.board }}-debug.zip build-${{ matrix.board }} || true

      - name: Archive workspace (always include for debugging)
        run: |
          echo "Creating workspace-debug.zip (excludes .git)"
          zip -r workspace-debug.zip . -x .git\* || true

      - name: Upload autoconf.h
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: autoconf-${{ matrix.board }}
          path: |
            build-${{ matrix.board }}/zephyr/include/generated/autoconf.h
            build-${{ matrix.board }}-debug.zip
            workspace-debug.zip
            build-${{ matrix.board }}.log

            
